### ISSUE TITLE
yyx-guildsnapshot-2.0.0-r2-Steam Not working as Intended.

### ISSUE THREAD

**Issue by seagull4896** [OnmyojiX/yyx-guildsnapshot#1]
The steam client has just been updated today. Judging from the appearance and version, this should be a similar version to the CN client. However, this happens when I attempt to use the snapshot. 
![Screenshot_896](https://user-images.githubusercontent.com/71395289/93356332-66a8d900-f882-11ea-9dc4-31328169b8f6.png)
I'm sorry for bothering you here but I'm not certain on where else to inform you of this issue.

**Comment by fluxxu** [comment]
Thanks for reporting, will check after work

**Comment by fluxxu** [comment]
https://github.com/OnmyojiX/yyx-guildsnapshot/releases/download/2.0.1/yyx-guildsnapshot-2.0.1-Steam.zip
Fixed @seagull4896

**Comment by seagull4896** [comment]
Thank you! It worked really well ^^
